blank_issues_enabled: true
contact_links:
  - name: Mellon Deliverable Tracking
    url: https://github.com/GreenhouseStudios/sourcery-web-app/wiki
    about: Tracking the progress of our deliverables is handled in the Wiki
#   - name: ğŸŒ Found a problem with nodejs.org beyond the API reference docs?
#     url: https://github.com/nodejs/nodejs.org/issues/new/choose
#     about: Please file an issue in the Node.js website repo.
