name: Deploy to Production Firebase Hosting

on:
  release:
    types: published

jobs:
  production:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout tagged release"
      uses: actions/checkout@v4

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - run: npm ci
    - run: npm run generate
      env:
        NODE_ENV: production
        BASE_URL: ${{ vars.BASE_URL }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}


    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUBE_1542818590717 }}'
        channelId: live
        projectId: tube-1542818590717
        target: tube-1542818590717
